CREATE TABLE Category (
    CategoryID SERIAL PRIMARY KEY NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Description VARCHAR(1000) NOT NULL
);

CREATE TABLE Image (
    ImageID SERIAL PRIMARY KEY NOT NULL,
    Name VARCHAR(100) NOT NULL,
    Description VARCHAR(MAX) NOT NULL,
    Content VARCHAR(MAX) NOT NULL,
    CategoryID INT REFERENCES CATEGORY(CategoryID) NOT NULL
);

CREATE TABLE Story (
    StoryID SERIAL PRIMARY KEY NOT NULL,
    Name VARCHAR(100) NOT NULL,
    Description VARCHAR(MAX) NOT NULL,
    Content VARCHAR(MAX) NOT NULL,
    CategoryID INT REFERENCES CATEGORY(CategoryID) NOT NULL
);

CREATE TABLE Video (
    VideoID SERIAL PRIMARY KEY NOT NULL,
    Name VARCHAR(100) NOT NULL,
    Description VARCHAR(MAX) NOT NULL,
    Content VARCHAR(MAX) NOT NULL,
    CategoryID INT REFERENCES CATEGORY(CategoryID) NOT NULL
);
